### ISSUE TITLE
Error while installing with PHP8

### ISSUE THREAD

**Issue by lichtner** [elastic/ecs-logging-php#30]
Could you add support for PHP 8?

```
$ composer require elastic/ecs-logging 
                                                                                                                           
[InvalidArgumentException]                                                                                                 
Package elastic/ecs-logging has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version 

$ php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:30) ( NTS )

$ composer -V
Composer version 2.0.12 2021-04-01 10:14:59
```

**Comment by Chaz0r** [comment]
Would be great if the PR gets a merge. We also want to upgrade to PHP8 and this library is a blocker for that :(

**Comment by SergeyKleyman** [comment]
I'll try to merge the PR ASAP.

**Comment by Chaz0r** [comment]
@SergeyKleyman great! Any idea when a version with that PR will be available? currently our system is broken. With that information I can clarify if I have to roll everything back or if I can wait for the new version.

**Comment by SergeyKleyman** [comment]
If the PR is good to merge I'll start a new release today (hopefully there won't be any issues).
My only concern is that CI doesn't test on PHP 8 yet. Did you try the library on PHP 8?

**Comment by Chaz0r** [comment]
I tried it locally and didn't have any issues there. But locally I don't have the complete feature set of our microservice infrastructure so this may not be perfectly valid

**Comment by SergeyKleyman** [comment]
[1.0.3 release](https://packagist.org/packages/elastic/ecs-logging#1.0.3) includes support for PHP 8.
