### ISSUE TITLE
Multiple monolog versions

### ISSUE THREAD

**Issue by pimjansen** [elastic/ecs-logging-php#8]
@philkra how are we going to handle multiple versions of frameworks? Since i see you included them in the dev deps. But installing multiple majors there will be a problem.

How will we handle that? I guess we should mock them instead instead of putting them as dev dependency isnt it?

**Comment by philkra** [comment]
Hi @pimjansen , I was doing some research and yes, we can only go down the mocking path .. there is no way to have multiple majors (as you stated) as dependencies
